<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jssm</string>
		<string>jssm_state</string>
	</array>
	<key>name</key>
	<string>JSSM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mn</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>block comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.jssm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>comment</key>
			<string>block comment</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.jssm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\${</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>js outcalls</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>semver</string>
			<key>match</key>
			<string>([0-9]*)(\.)([0-9]*)(\.)([0-9]*)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>jssm language tokens</string>
			<key>match</key>
			<string>graph_layout(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.jssmLanguage</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>jssm language tokens</string>
			<key>match</key>
			<string>machine_name(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.jssmLanguage</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>jssm language tokens</string>
			<key>match</key>
			<string>machine_version(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.jssmLanguage</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>jssm language tokens</string>
			<key>match</key>
			<string>jssm_version(\s*)(:)</string>
			<key>name</key>
			<string>constant.language.jssmLanguage</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;-&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.legal_legal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;-</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.legal_none</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>-&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.none_legal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;=&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.main_main</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>=&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.none_main</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;=</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.main_none</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;~&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.forced_forced</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>~&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.none_forced</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;~</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.forced_none</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;-=&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.legal_main</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;=-&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.main_legal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;-~&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.legal_forced</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;~-&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.forced_legal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;=~&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.main_forced</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transitions</string>
			<key>match</key>
			<string>&lt;~=&gt;</string>
			<key>name</key>
			<string>keyword.control.transition.jssmArrow.forced_main</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>edge probability annotation</string>
			<key>match</key>
			<string>([0-9]+)%</string>
			<key>name</key>
			<string>constant.numeric.jssmProbability</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>action annotation</string>
			<key>match</key>
			<string>\'[^']*\'</string>
			<key>name</key>
			<string>constant.character.jssmAction</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>jssm label annotation</string>
			<key>match</key>
			<string>\"[^"]*\"</string>
			<key>name</key>
			<string>entity.name.tag.jssmLabel.doublequoted</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>jssm label annotation</string>
			<key>match</key>
			<string>([a-zA-Z0-9_.+&amp;()#@!?,])</string>
			<key>name</key>
			<string>entity.name.tag.jssmLabel.atom</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jssm</string>
	<key>uuid</key>
	<string>2bb22b55-e811-4383-9929-ae6d0ab92aca</string>
</dict>
</plist>
